version: '3'

services:
  mongo:
    image: mongo
    container_name: 'sales-mongodb'
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks: 
      sales-net:
        ipv4_address: 10.5.0.2

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: 'sales-zookeeper'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks: 
      sales-net:
        ipv4_address: 10.5.0.3

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: 'sales-kafka'
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks: 
      sales-net:
        ipv4_address: 10.5.0.4

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: 'sales-kafdrop'
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
    networks: 
      sales-net:
        ipv4_address: 10.5.0.5

  sales-service:
    container_name: sales-service
    depends_on: 
      - mongo
      - zookeeper
      - kafka
      - kafdrop
    build:
      context: ./sales-service/
    ports:
      - "8080:8080"
    environment:
      MONGO_URL: mongo
      KAFKA_URL: kafka
    networks: 
      sales-net:
        ipv4_address: 10.5.0.6
      
networks:
  sales-net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16