spring:
  application:
    name: sales-service
    port: 8080
  data:
    mongodb:
      uri: mongodb://root:password@${MONGO_URL:localhost}:27017/admin
      database: admin

springdoc:
  swagger-ui:
    path: /swagger-ui.html

sales:
  score:
    minimum-valid: 61
  scheduler:
    analyze-sales-scores-milliseconds-time: 60000 # 1 min

kafka:
  bootstrap-servers: ${KAFKA_URL:localhost}:9092
  sales-person-validation-request-topic: sales-person-validation-request-topic
  sales-judicial-validation-request-topic: sales-judicial-validation-request-topic
  consumer-group: sales-service

client:
  person-service:
    url: http://vg8j7.mocklab.io
  judicial-service:
    url: http://vg8j7.mocklab.io
  analysis-service:
    url: http://vg8j7.mocklab.io
